### PR TITLE
commented out '`console.log`' lines

### PR DESCRIPTION
**Pull request by humzashah**
~~console.log() calls might be useful indicators in development but not a preferable thing to have in production code. commenting out instead of removing them for easy-inclusion later.~~

[removed `console.log` from the `build/slideme.min.js` file](https://github.com/InnovationEnterprise/slideme-ie/pull/32#issuecomment-163018370)

### CODE REVIEW

**Comment by humzashah** [comment]
@xoxoxo kindly have a look and let me know if this is useful or not

**Comment by xoxoxo** [comment]
well to me its very useful and cant find anything against. if anybody would like to implement slideme without digging into code that could help him a lot.
Its not like we are displaying alert('dupa'); x100
We can remove it form minified version.

Thoughts, anybody else?

**Comment by humzashah** [comment]
@xoxoxo i meant let me know if my change is useful or not, as i wasn't 100% sure myself. :)

indeed the `console.log()` will assist any developer when he/she is building upon this project if these messages are placed strategically rather than randomly for quick debugging. if this is the case then i'm all for keeping them in as they are and removing them from the minimized js files.

**Comment by humzashah** [comment]
@xoxoxo @tosbourn @derekjohnson

**Comment by tosbourn** [comment]
I'm confused. The diff isn't showing any commented out lines for `build/slideme.dev.js` @humzashah. Maybe this was addressed elsewhere?

**Comment by humzashah** [comment]
@tosbourn [here's](https://github.com/InnovationEnterprise/slideme-ie/commit/ed10fda0eb6ad2ad9212beba8a31e6d3de6ee868) my first commit

**Comment by tosbourn** [comment]
@humzashah could someone else have been making a similar change either directly to master or something? The full diff for this PR doesn't include those changes.

https://github.com/InnovationEnterprise/slideme-ie/pull/32/files

Happy to :+1:  but it looks like we will just be committing removing some whitespace (which I am all for!)

**Comment by humzashah** [comment]
@tosbourn no, that was my first commit. my second commit was to uncomment my comments. :P
my third commit was simply to remove the `console.log`s from the minified JS file. you can check this from the `commits` tab on top of this PR

**Comment by tosbourn** [comment]
Ahh with you. Sorry.

:+1:

**Comment by humzashah** [comment]
@xoxoxo leaving the `merge` up to you, if you think all is ok

**Comment by xoxoxo** [comment]
Ill add this as a gulp task (or you can). Closing for now.

@humzashah

**Pull request closed without merging**
